contactproject/contactapp/urls.py
from django.urls import path
from .views import *

app_name = 'contactapp'
urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('contacts/', ContactListView.as_view(), name="contacts"),
    path('contacts/about', ContactAboutView.as_view(), name="contactabout"),
    path('contacts/search', ContactSearchView.as_view(), name="search"),
    path('contacts/add-new/',
         ContactCreateView.as_view(), name="contactcreate"),
    path('contacts/<int:pk>/update/',
         ContactUpdateView.as_view(), name="contactupdate"),
    path('contacts/<int:pk>/delete/',
         ContactDeleteView.as_view(), name="contactdelete"),

    path('contacts/<email>/send-message/',
         SendEmailView.as_view(), name="sendemail"),
]

contactproject/contactproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contactapp.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contactproject/contactapp/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=400, null=True, blank=True)
    mobile1 = models.CharField(max_length=10)
    mobile2 = models.CharField(max_length=10, null=True, blank=True)
    email1 = models.EmailField(null=True, blank=True)
    email2 = models.EmailField(null=True, blank=True)
    image = models.ImageField(upload_to="contacts", null=True, blank=True)

    def __str__(self):
        return self.name

contactproject/contactapp/forms.py
from django import forms
from .models import *


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = "Enter " + field_name + "..."


class ReplyForm(forms.Form):
    subject = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    message = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control'
    }))

contactproject/contactapp/views.py
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import *
from .models import *
from django.core.mail import send_mail
from django.conf import settings
from .forms import *
from django.db.models import Q
import requests


class HomeView(TemplateView):
    template_name = "home.html"


class ContactListView(TemplateView):
    template_name = "contacts.html"
    success_message = "messages was send successfully"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.GET:

            q = self.request.GET["w"]
            results = Contact.objects.filter(
                Q(name__contains=q) | Q(email1__contains=q) |
                Q(mobile1__contains=q) | Q(address__contains=q))
        else:
            results = Contact.objects.all()

        resp = requests.get("https://ratopati.com/jsonapi/get_recent_posts/")
        data = resp.json()
        context['allnews'] = data['posts']
        context['allcontacts'] = results

        return context
    # def form_valid(self, form):
    #     fnames = form.cleaned_data['name']
    #     messages = form.cleaned_data['message']

    #     send_mail(
    #         fnames + ", ",
    #         messages,

    #         settings.EMAIL_HOST_USER,
    #         ["aryalpooja89@gmail.com"],
    #         fail_silently=False

    #     )

    #     return super().form_valid(form)


class ContactCreateView(CreateView):
    template_name = "contactcreate.html"
    form_class = ContactForm
    success_url = reverse_lazy("contactapp:contacts")


class ContactUpdateView(UpdateView):
    template_name = "contactcreate.html"
    form_class = ContactForm
    model = Contact
    success_url = reverse_lazy("contactapp:contacts")


class ContactDeleteView(DeleteView):
    template_name = "contactdelete.html"
    model = Contact
    success_url = reverse_lazy("contactapp:contacts")


class SendEmailView(FormView):
    template_name = "contactreply.html"
    form_class = ReplyForm
    success_url = reverse_lazy("contactapp:contacts")

    def form_valid(self, form):
        sub = form.cleaned_data['subject']
        mess = form.cleaned_data['message']
        email = self.kwargs['email']
        print(sub, mess, email)

        send_mail(
            sub,
            mess,
            settings.EMAIL_HOST_USER,
            [email],
            fail_silently=False
        )
        return super().form_valid(form)


class ContactSearchView(TemplateView):
    template_name = "contactsearch.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        q = self.request.GET["w"]
        results = Contact.objects.filter(
            Q(name__contains=q) | Q(email1__contains=q) |
            Q(mobile1__contains=q) | Q(address__contains=q))
        context['results'] = results

        return context

class ContactAboutView(TemplateView):
    template_name="contactabout.html"

contactproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
</head>
<body class="container-fluid">
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'contactapp:home' %}">Contact Management System</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'contactapp:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'contactapp:contacts' %}">Contact List</a>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'contactapp:search' %}">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="w">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
	{% block content %}

	{% endblock %}


<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script type="text/javascript" src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
{% block js %}
{% endblock %}

</body>
</html>

contactproject/templates/contactabout.html
{% extends 'base.html' %}

{% block title %}Add new contact{% endblock %}


{% block content %}

{% endblock %}

contactproject/templates/contactcreate.html
{% extends 'base.html' %}

{% block title %}Add new contact{% endblock %}


{% block content %}

<div class="row">
	<div class="col-md-4 mx-auto">
		<div class="shadow-none mb-4" bg-light>
		 <h4>Contact Form</h4>
		 <form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{form.as_p}}
		 	<button class="btn btn-info btn-block">Submit</button>
		 </form>
		</div> 
	</div>
</div>
{% endblock %}

contactproject/templates/contactdelete.html
{% extends 'base.html' %}

{% block title %}Delete contact{% endblock %}


{% block content %}

<form method="POST">
	{% csrf_token%}
	<h3>Are you sure</h3>
	<button class="btn btn-danger">Yes</button>
	<a class="btn btn-info" href="{% url 'contactapp:contacts' %}">No</a>
</form>
{% endblock %}

contactproject/templates/contactreply.html
{% extends 'base.html' %}

{% block title %}reply contact{% endblock %}


{% block content %}

<div class="row">
	<div class="col-md-4 mx-auto">
		<div class="shadow-none mb-4" bg-light>
		 <h4>Reply Form</h4>
		 <form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{form.as_p}}
		 	<button class="btn btn-info btn-block">Submit</button>
		 </form>
		</div> 
	</div>
</div>

{% endblock %}

contactproject/templates/contacts.html
{% extends 'base.html' %}

{% block title %}Contact List{% endblock %}


{% block content %}
<a href="{% url 'contactapp:contactcreate' %}"><span style="font-size: 40px;" class="fa fa-plus-circle"></span></a>
<h3>Contact List</h3>
<table class="table">
	<thead>
		<tr>
			<th>SN</th>
			<th>Name</th>
			<th>Mobile</th>
			<th>Email</th>
			<th>Address</th>
			<th>Image</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		{% for contact in allcontacts %}
		
		<tr>
			<td>{{forloop.counter}}</td>
			<td>{{contact.name}}</td>
			<td>{{contact.mobile1}}</td>
			<td>{{contact.email1}}</td>
			<td>{{contact.address}}</td>
			<td><img src="{{contact.image.url}}" width="75"></td>
			<td>
				<a class="btn btn-info" href="{% url 'contactapp:contactupdate' contact.pk %}"><i class="fa fa-pencil"></i></a>
				<a class="btn btn-danger" href="{% url 'contactapp:contactdelete' contact.pk %}"><i class="fa fa-trash"></i></a>
				<a class="btn btn-success" href="{% url 'contactapp:sendemail' contact.email1 %}"><i class="fa fa-envelope"></i></a>

			</td>
		</tr>
		{% endfor %}
	
	</tbody>
</table>

<h3>News List</h3>
<table class="table">
	<thead>
		<tr>
			<th>SN</th>
			<th>Name</th>
			<th>Mobile</th>
			<th>Email</th>
			<th>Address</th>
			<th>Image</th>
		</tr>
	</thead>
	<tbody>
		{% for news in allnews %}
		
		<tr>
			<td>{{forloop.counter}}</td>
			<td>{{news.title}}</td>
			<td>{{news.mobile1}}</td>
			<td>{{news.email1}}</td>
			<td>{{news.address}}</td>
			<td><img src="{{news.title_photo}}" width="75"></td>
			
		</tr>
		{% endfor %}
	
	</tbody>
</table>
{% endblock %}
{% block js %}
<script type="text/javascript">
	$(document).ready( function () {
	    $('.table').DataTable();
	} );
</script>

{% endblock %}

contactproject/templates/contactsearch.html
{% extends 'base.html' %}

{% block title %}Search result{% endblock %}


{% block content %}

<h3>Search items</h3>

{% for res in results %}

<li>{{res.name}}</li>
<img src="{{res.image.url}}" width="400">

{% endfor %}

{% endblock %}

contactproject/templates/home.html
{% extends 'base.html' %}


{% block title %}Home{% endblock %}

{% block content %}
<h3>This is home page</h3>

{% endblock %}